parameters:
#    backend_admin.example.class: Backend\AdminBundle\Example

services:
#    backend_admin.example:
#        class: %backend_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
